//! Golden diff: `patch_xml` applied to the raw `word/document.xml` must be
//! byte-for-byte identical to the output of upstream docxtpl 0.20.2
//! `DocxTemplate.patch_xml`
//! (`tests/fixtures/stages/<id>.full_patched.xml`). Goldens are generated by
//! `tests/fixtures/dump_stages.py`; do not modify them or relax the
//! comparison.

use docxtpl_compat::patch_xml;
use std::fs;
use std::io::Read as _;
use std::path::{Path, PathBuf};

const STAGES_DIR: &str = concat!(env!("CARGO_MANIFEST_DIR"), "/../../tests/fixtures/stages");
const TEMPLATES_DIR: &str = concat!(
    env!("CARGO_MANIFEST_DIR"),
    "/../../tests/fixtures/templates"
);
const MANIFEST_PATH: &str = concat!(
    env!("CARGO_MANIFEST_DIR"),
    "/../../tests/fixtures/manifest.json"
);

const GOLDEN_SUFFIX: &str = ".full_patched.xml";

/// Enumerates all `<id>.full_patched.xml` files in the stages directory,
/// sorted by id.
fn list_golden_ids() -> Vec<String> {
    let mut ids: Vec<String> = fs::read_dir(STAGES_DIR)
        .expect("stages directory exists")
        .filter_map(std::result::Result::ok)
        .filter_map(|entry| {
            let name = entry.file_name().to_string_lossy().into_owned();
            name.strip_suffix(GOLDEN_SUFFIX).map(str::to_owned)
        })
        .collect();
    ids.sort();
    ids
}

/// The manifest is the single source of truth for the fixture set; adding
/// new render cases does not require changing hardcoded counts in the
/// tests.
fn manifest_render_ids() -> Vec<String> {
    let bytes = fs::read(MANIFEST_PATH).expect("read fixture manifest");
    let manifest: serde_json::Value =
        serde_json::from_slice(&bytes).expect("parse fixture manifest");
    let mut ids: Vec<String> = manifest["fixtures"]
        .as_array()
        .expect("manifest.fixtures is an array")
        .iter()
        .filter(|fixture| fixture["mode"] == "render")
        .map(|fixture| {
            fixture["id"]
                .as_str()
                .expect("fixture.id is a string")
                .to_owned()
        })
        .collect();
    ids.sort();
    ids
}

/// Reads the raw UTF-8 `word/document.xml` from the template docx.
fn read_document_xml(id: &str) -> Vec<u8> {
    let path = Path::new(TEMPLATES_DIR).join(format!("{id}.docx"));
    let file = fs::File::open(&path).unwrap_or_else(|e| panic!("open {}: {e}", path.display()));
    let mut archive = zip::ZipArchive::new(file).expect("open docx zip");
    let mut entry = archive
        .by_name("word/document.xml")
        .expect("docx contains word/document.xml");
    let mut bytes = Vec::with_capacity(usize::try_from(entry.size()).unwrap_or(0));
    entry.read_to_end(&mut bytes).expect("read document.xml");
    bytes
}

fn golden_path(id: &str) -> PathBuf {
    Path::new(STAGES_DIR).join(format!("{id}{GOLDEN_SUFFIX}"))
}

/// Extracts at most 80 characters on each side of the byte offset, aligned
/// to UTF-8 character boundaries.
fn context_around(text: &str, offset: usize) -> String {
    let mut center = offset.min(text.len());
    while center < text.len() && !text.is_char_boundary(center) {
        center += 1;
    }

    let mut start = center;
    for _ in 0..80 {
        match text[..start].chars().next_back() {
            Some(ch) => start -= ch.len_utf8(),
            None => break,
        }
    }
    let mut end = center;
    for _ in 0..80 {
        match text[end..].chars().next() {
            Some(ch) => end += ch.len_utf8(),
            None => break,
        }
    }
    text[start..end].replace('\r', "\\r").replace('\n', "\\n")
}

#[test]
fn golden_set_is_complete() {
    let ids = list_golden_ids();
    let expected = manifest_render_ids();
    assert_eq!(
        ids, expected,
        "the full_patched golden set must correspond one-to-one with the manifest's render fixtures"
    );
}

#[test]
fn patch_xml_matches_every_golden_byte_for_byte() {
    let ids = list_golden_ids();
    assert_eq!(ids, manifest_render_ids());

    let mut failures: Vec<String> = Vec::new();
    for id in &ids {
        let raw_bytes = read_document_xml(id);
        let raw = String::from_utf8(raw_bytes).expect("document.xml is UTF-8");
        let patched = patch_xml(&raw);
        let golden_bytes = fs::read(golden_path(id)).expect("read golden file");

        if patched.as_bytes() != golden_bytes.as_slice() {
            let golden = String::from_utf8_lossy(&golden_bytes);
            let first_diff = patched
                .as_bytes()
                .iter()
                .zip(golden_bytes.iter())
                .position(|(a, b)| a != b)
                .unwrap_or_else(|| patched.len().min(golden_bytes.len()));
            failures.push(format!(
                "id={id} first differing byte offset={first_diff}\n  got({}B): {}\n  exp({}B): {}",
                patched.len(),
                context_around(&patched, first_diff),
                golden_bytes.len(),
                context_around(&golden, first_diff),
            ));
        }
    }

    assert!(
        failures.is_empty(),
        "{} golden(s) not byte-for-byte aligned (out of {}):\n{}",
        failures.len(),
        ids.len(),
        failures.join("\n")
    );
}

#[test]
fn patching_golden_outputs_again_does_not_panic() {
    // Idempotency is not required; only that calling patch_xml again on any
    // golden output does not panic.
    for id in list_golden_ids() {
        let golden = fs::read_to_string(golden_path(&id)).expect("read golden file");
        let _ = patch_xml(&golden);
    }
}
