# -*- coding: utf-8 -*-
"""P4 fixture context (generated by tests/fixtures/generate.py; do not edit by hand).

Provides build_context(tpl): returns the render context, which may contain
typed values such as RichText/RichTextParagraph/Listing/InlineImage/Subdoc
(matching upstream docxtpl 0.20.2 usage).
"""
import io
import os

from docx.shared import Mm
from docxtpl import InlineImage, Listing, RichText, RichTextParagraph

_HERE = os.path.dirname(os.path.abspath(__file__))


def _img(name):
    return os.path.join(_HERE, os.pardir, "media", name)


def _sub(name):
    return os.path.join(_HERE, os.pardir, "templates", name)


def _media_path(name):
    """Absolute path to material under tests/fixtures/media (P7: path arguments of replace_*)."""
    return os.path.join(_HERE, os.pardir, "media", name)


def _media_bytes(name):
    """Bytes of material under tests/fixtures/media (P7: wrapped in BytesIO for file-like arguments)."""
    with open(_media_path(name), "rb") as fh:
        return fh.read()

def build_context(tpl):
    # Upstream replace_embedded accepts only a file path for dst; src may be
    # file-like.
    tpl.replace_embedded(io.BytesIO(_media_bytes("p7_embed_orig1.bin")),
                         _media_path("p7_embed_new1.bin"))
    tpl.replace_zipname("word/embeddings/p7_ole2.bin",
                        _media_path("p7_embed_new2.bin"))
    return {"e": "embedded replacement"}
