# -*- coding: utf-8 -*-
"""P4 fixture context (generated by tests/fixtures/generate.py; do not edit by hand).

Provides build_context(tpl): returns the render context, which may contain
typed values such as RichText/RichTextParagraph/Listing/InlineImage/Subdoc
(matching upstream docxtpl 0.20.2 usage).
"""
import io
import os

from docx.shared import Mm
from docxtpl import InlineImage, Listing, RichText, RichTextParagraph

_HERE = os.path.dirname(os.path.abspath(__file__))


def _img(name):
    return os.path.join(_HERE, os.pardir, "media", name)


def _sub(name):
    return os.path.join(_HERE, os.pardir, "templates", name)


def _media_path(name):
    """Absolute path to material under tests/fixtures/media (P7: path arguments of replace_*)."""
    return os.path.join(_HERE, os.pardir, "media", name)


def _media_bytes(name):
    """Bytes of material under tests/fixtures/media (P7: wrapped in BytesIO for file-like arguments)."""
    with open(_media_path(name), "rb") as fh:
        return fh.read()

def build_context(tpl):
    return {"alerts": [
        {"date": "2015-03-10",
         "desc": RichText("Very critical alert", color="FF0000", bold=True),
         "type": "CRITICAL", "bg": "FF0000"},
        {"date": "2015-03-11", "desc": RichText("Just a warning"),
         "type": "WARNING", "bg": "FFDD00"},
        {"date": "2015-03-12", "desc": RichText("Information"),
         "type": "INFO", "bg": "8888FF"},
        {"date": "2015-03-13", "desc": RichText("Debug trace"),
         "type": "DEBUG", "bg": "FF00FF"},
    ]}
