//! P1 acceptance: real fixture templates (generated by python-docx) go through
//! docxtpl-opc open → validate → write → reopen; the part set and every
//! unmodified part's bytes must match exactly.
//! Corresponds to P1 in the planning doc: "at least 20 templates pass
//! unrendered round trips with package validation: no unknown parts lost,
//! no dangling relationships".

use std::fs;
use std::path::PathBuf;

use docxtpl_opc::{Package, PackageLimits};

fn fixtures_dir() -> PathBuf {
    // CARGO_MANIFEST_DIR = <repo>/crates/docxtpl-opc
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("..")
        .join("..")
        .join("tests")
        .join("fixtures")
        .join("templates")
}

#[test]
fn roundtrip_all_rt_fixtures_byte_identical() {
    let dir = fixtures_dir();
    let mut ids: Vec<String> = fs::read_dir(&dir)
        .unwrap_or_else(|e| panic!("cannot read fixture directory {}: {e}", dir.display()))
        .filter_map(Result::ok)
        .map(|e| e.file_name().to_string_lossy().into_owned())
        .filter(|n| n.starts_with("rt_") && n.ends_with(".docx"))
        .collect();
    ids.sort();

    // P1 acceptance threshold: at least 20 round-trip templates
    assert!(
        ids.len() >= 20,
        "fewer than 20 rt_* fixtures (got {}); P1 acceptance is not met",
        ids.len()
    );

    let limits = PackageLimits::default();
    let mut ok = 0usize;
    for name in &ids {
        let path = dir.join(name);
        let pkg =
            Package::open(&path, &limits).unwrap_or_else(|e| panic!("{name}: failed to open: {e}"));
        pkg.validate().unwrap_or_else(|e| {
            panic!("{name}: validate failed (unknown part lost/dangling relationship): {e}")
        });
        assert!(
            pkg.main_document_uri().is_ok(),
            "{name}: missing officeDocument relationship"
        );

        // Record the original (part name, bytes)
        let mut before: Vec<(String, Vec<u8>)> = pkg
            .parts()
            .map(|p| (p.name().to_string(), p.bytes().unwrap().to_vec()))
            .collect();
        before.sort();

        let tmp = tempfile::NamedTempFile::new().unwrap();
        pkg.save(tmp.path())
            .unwrap_or_else(|e| panic!("{name}: failed to write: {e}"));

        let reopened = Package::open(tmp.path(), &limits)
            .unwrap_or_else(|e| panic!("{name}: failed to reopen: {e}"));
        reopened
            .validate()
            .unwrap_or_else(|e| panic!("{name}: validate failed after reopen: {e}"));

        let mut after: Vec<(String, Vec<u8>)> = reopened
            .parts()
            .map(|p| (p.name().to_string(), p.bytes().unwrap().to_vec()))
            .collect();
        after.sort();

        let before_names: Vec<&String> = before.iter().map(|(n, _)| n).collect();
        let after_names: Vec<&String> = after.iter().map(|(n, _)| n).collect();
        assert_eq!(before_names, after_names, "{name}: part sets do not match");
        for ((bn, bb), (an, ab)) in before.iter().zip(after.iter()) {
            assert_eq!(bn, an);
            assert_eq!(
                bb, ab,
                "{name}: part {bn} bytes changed after round trip (unmodified parts must be preserved verbatim)"
            );
        }
        ok += 1;
    }
    eprintln!("P1 round-trip fixtures passed: {ok}/{}", ids.len());
}
