//! 上游 `DocxTemplate.render_properties` 的移植（template.py L333–358）。
//!
//! 每次 render 上游都会把 6 个字符串型核心属性当 Jinja 模板渲染后写回：
//! 缺省元素（如 dc:identifier / dc:language）会因此被创建为空元素。
//! 核心属性 part 使用严格解析（原始 part 良构），不做 recover。

use docxtpl_xml::XmlDocument;
use docxtpl_xml::XmlLimits;
use minijinja::Environment;
use serde_json::Value as JsonValue;

use crate::error::RenderError;
use crate::render::{build_jinja_env, render_inline};

/// Dublin Core 元素命名空间（dc:title 等）。
const DC_NS: &str = "http://purl.org/dc/elements/1.1/";

/// 核心属性 part 名。
pub const CORE_PART: &str = "docProps/core.xml";

/// (上游 properties 列表顺序, dc 本地名)。
/// python-docx 属性名 → OOXML 元素名：
/// author→creator、comments→description，其余同名。
const PROPERTIES: [(&str, &str); 6] = [
    ("author", "creator"),
    ("comments", "description"),
    ("identifier", "identifier"),
    ("language", "language"),
    ("subject", "subject"),
    ("title", "title"),
];

/// 渲染 docProps/core.xml（对齐上游默认行为：autoescape 不作用于属性渲染，
/// jinja_env 缺省时 `Environment()`）。
pub fn render_core_properties(
    src_xml: &str,
    context: &JsonValue,
    autoescape: bool,
) -> Result<String, RenderError> {
    let mut doc = XmlDocument::parse_strict(src_xml, &XmlLimits::default()).map_err(|e| {
        RenderError::Xml {
            part: CORE_PART.to_string(),
            source: e,
        }
    })?;

    let env: Environment<'static> = build_jinja_env(autoescape);
    let root = doc.root();

    for (_python_name, local) in PROPERTIES {
        let existing = doc.children(root).iter().copied().find(|&c| {
            doc.tag(c)
                .is_some_and(|q| q.ns == DC_NS && q.local == local)
        });
        // python-docx 对这些文本型属性的缺省值为空串（getter 返回 ''）。
        let initial = existing.map_or(String::new(), |id| {
            doc.element_text(id)
                .map_or_else(String::new, str::to_string)
        });
        let rendered = render_inline(&env, &initial, context, CORE_PART)?;
        let element = match existing {
            Some(id) => id,
            None => {
                // 缺省元素：按上游 setattr 行为新建并追加到根（dc 前缀须已声明）。
                let new_id = doc
                    .new_prefixed_element("dc", DC_NS, local, Vec::new())
                    .map_err(|e| RenderError::Xml {
                        part: CORE_PART.to_string(),
                        source: e,
                    })?;
                doc.append_child(root, new_id);
                new_id
            }
        };
        doc.set_element_text(element, &rendered);
    }

    Ok(doc.serialize())
}

#[cfg(test)]
mod tests {
    use super::*;
    use docxtpl_xml::XmlLimits;
    use serde_json::json;

    fn dc_text(xml_out: &str, local: &str) -> Option<String> {
        let doc = XmlDocument::parse_strict(xml_out, &XmlLimits::default()).unwrap();
        doc.children(doc.root())
            .iter()
            .copied()
            .find(|&c| {
                doc.tag(c)
                    .is_some_and(|q| q.ns == DC_NS && q.local == local)
            })
            .map(|c| doc.element_text(c).unwrap_or("").to_string())
    }

    const SAMPLE: &str = concat!(
        "<?xml version='1.0' encoding='UTF-8' standalone='yes'?>",
        "<cp:coreProperties",
        " xmlns:cp=\"http://schemas.openxmlformats.org/package/2006/metadata/core-properties\"",
        " xmlns:dc=\"http://purl.org/dc/elements/1.1/\">",
        "<dc:creator>python-docx</dc:creator>",
        "<dc:description>generated by python-docx</dc:description>",
        "<dc:title></dc:title><cp:category/>",
        "</cp:coreProperties>"
    );

    #[test]
    fn creates_missing_properties_and_keeps_existing() {
        let out = render_core_properties(SAMPLE, &json!({}), false).unwrap();
        // 已存在的值原样保留（jinja 身份渲染）。
        assert_eq!(dc_text(&out, "creator").as_deref(), Some("python-docx"));
        assert_eq!(
            dc_text(&out, "description").as_deref(),
            Some("generated by python-docx")
        );
        // 上游 setattr 副作用：缺失的 identifier/language 被补为空元素。
        assert_eq!(dc_text(&out, "identifier").as_deref(), Some(""));
        assert_eq!(dc_text(&out, "language").as_deref(), Some(""));
        assert_eq!(dc_text(&out, "title").as_deref(), Some(""));
        // 新元素追加在根末尾，且 identifier 在 language 之前（properties 列表序）。
        let i = out.find("<dc:identifier").unwrap();
        let l = out.find("<dc:language").unwrap();
        assert!(i < l);
    }

    #[test]
    fn renders_jinja_in_property_values() {
        let xml = SAMPLE.replace("<dc:title></dc:title>", "<dc:title>{{ x }}</dc:title>");
        let out = render_core_properties(&xml, &json!({"x": "你好"}), false).unwrap();
        assert_eq!(dc_text(&out, "title").as_deref(), Some("你好"));
    }
}
